import os
try:
    from dotenv import load_dotenv
except ModuleNotFoundError:
    def load_dotenv(*args, **kwargs):
        return False
from pathlib import Path

# Load environment variables from .env (e.g., OPENAI_API_KEY)
load_dotenv()

import random

from memory.AdversarialMemory import AdversarialMemory
from meta.PatchMetaController import PatchEvalResult, PatchMetaController
from blue_team.BlueCommittee import BlueCommittee
from red_team.DistractorInjection import DistractorInjection
from red_team.FormatConstraint import FormatConstraint
from red_team.LogicInversion import LogicInversion
# Import shared core API and prompt manager layers
from core.LLMClient import LLMClient
from core.PromptManager import PromptManager
from config.experiments import experiment_flags_to_dict, resolve_experiment_flags
from scripts.evaluate import run_evaluation, is_correct_response
from config.settings import (
    AUTO_GENERATE_BENCHMARK,
    BENCHMARK_SOURCE,
    ADV_TEST_SET_PATH,
    CLEAN_TEST_SET_PATH,
    EVAL_MAX_SAMPLES,
    EVAL_RANDOM_SEED,
    EXPERIMENT_PRESET,
    OUTPUT_DIR,
    TRAIN_SET_PATH,
    VAL_SET_PATH,
    TEST_SET_PATH,
    get_model_name,
)

import json

# ==================== Data loading ====================
DATA_PATH = TRAIN_SET_PATH
_dataset = None

def get_random_seed_question():
    """Randomly sample a seed question and answer from train.json."""
    global _dataset
    if _dataset is None:
        if os.path.exists(DATA_PATH):
            with open(DATA_PATH, 'r', encoding='utf-8') as f:
                _dataset = json.load(f)
        else:
            print(f"[Warning] Data file not found: {DATA_PATH}. Falling back to a mock sample.")
            _dataset = [{"question": "1+1=?", "answer": "2"}]
            
    item = random.choice(_dataset)
    return item["question"], str(item["answer"])

def evaluate_answer(target_response: str, correct_answer: str) -> bool:
    """Simple correctness check: target response contains the answer."""
    return str(correct_answer) in target_response

def passes_regression_test(new_prompt: str, threshold: float, model_name: str | None) -> bool:
    """
    Regression test to prevent catastrophic forgetting.
    Evaluate the new prompt on a clean validation set and reject if accuracy drops too far.
    """
    if not os.path.exists(VAL_SET_PATH):
        print("  -> [Warning] No validation set found; skipping regression test.")
        return True

    print("  -> [Regression] Evaluating new prompt on clean validation set...")
    val_acc = run_evaluation(new_prompt, VAL_SET_PATH, log=True, model_name=model_name)
    print(f"  -> [Regression] Val accuracy: {val_acc * 100:.1f}%")

    if val_acc >= threshold:
        return True
    else:
        return False


def evaluate_clean_guard(
    new_prompt: str,
    threshold: float,
    model_name: str | None,
    reference_clean_acc: float | None = None,
) -> dict:
    """
    Clean-accuracy guard for patch admission.
    Returns the measured clean accuracy and the drop against the current clean reference.
    """
    if not os.path.exists(VAL_SET_PATH):
        print("  -> [Clean Guard] No validation set found; skipping clean guard.")
        return {
            "passed": True,
            "new_clean_acc": reference_clean_acc,
            "clean_drop": 0.0,
        }

    print("  -> [Clean Guard] Evaluating candidate patch on clean validation set...")
    new_clean_acc = run_evaluation(new_prompt, VAL_SET_PATH, log=True, model_name=model_name)
    clean_drop = 0.0
    if reference_clean_acc is not None:
        clean_drop = max(0.0, reference_clean_acc - new_clean_acc)

    print(
        "  -> [Clean Guard] "
        f"new_clean_acc={new_clean_acc:.3f}, clean_drop={clean_drop:.3f}, threshold={threshold:.3f}"
    )
    return {
        "passed": new_clean_acc >= threshold,
        "new_clean_acc": new_clean_acc,
        "clean_drop": clean_drop,
    }


def _run_autogenerated_benchmark() -> None:
    if BENCHMARK_SOURCE.lower() == "bbh":
        from scripts.setup_bbh_ablation import setup_bbh_ablation

        print("[Dataset] Auto-generating BBH ablation train/val/test splits...")
        setup_bbh_ablation()
    elif BENCHMARK_SOURCE.lower() == "multitask":
        from scripts.generate_multitask_benchmark import generate_multitask_benchmark

        print("[Dataset] Auto-generating multitask train/val/test splits...")
        generate_multitask_benchmark()
    else:
        from scripts.generate_benchmark import generate_benchmark

        print("[Dataset] Auto-generating benchmark train/val/test splits...")
        generate_benchmark()

# ==================== Config & entrypoint ====================
MAX_EPOCHS = int(os.environ.get("EVOLUTION_ROUNDS", "5"))
CANDIDATE_PATCHES_PER_ROUND = int(os.environ.get("CANDIDATE_PATCHES_PER_ROUND", "4"))

def main():
    print("========== S-MAPE adversarial evolution started ==========")

    experiment_flags = resolve_experiment_flags(EXPERIMENT_PRESET)
    print(f"[Setup] Experiment preset: {EXPERIMENT_PRESET}")
    print(f"[Setup] Experiment flags: {experiment_flags_to_dict(experiment_flags)}")

    if AUTO_GENERATE_BENCHMARK:
        _run_autogenerated_benchmark()

    output_dir = Path(OUTPUT_DIR)
    output_dir.mkdir(parents=True, exist_ok=True)
    
    # 1. Instantiate core components
    target_model_name = get_model_name("target")
    red_model_name = get_model_name("red")

    llm_client = LLMClient(role="target")
    patch_llm_client = LLMClient(role="patch")
    red_llm_client = LLMClient(role="red")
    prompt_manager = PromptManager(prompt_dir="_prompts")
    target_model = llm_client
    
    # 2. Instantiate red/blue teams, judge, and memory
    memory = AdversarialMemory(metrics_file=str(output_dir / "metrics.jsonl"))
    blue_committee = BlueCommittee(llm_client, prompt_manager, patch_llm_client=patch_llm_client)
    patch_meta_controller = PatchMetaController()
    
    red_operators = [
        DistractorInjection(red_llm_client),
        LogicInversion(red_llm_client),
        FormatConstraint(red_llm_client)
    ]
    
    def select_red_operator():
        weights = []
        for op in red_operators:
            score = memory.red_team_scores.get(op.__class__.__name__, 0)
            weight = max(0.1, score + 1.0)
            weights.append(weight)
        return random.choices(red_operators, weights=weights, k=1)[0]

    last_val_acc = None
    last_train_acc = None
    blue_trigger_count = 0
    blue_merge_count = 0
    blue_reject_count = 0
    blue_error_count = 0
        
    clean_eval_path = CLEAN_TEST_SET_PATH if os.path.exists(CLEAN_TEST_SET_PATH) else VAL_SET_PATH
    adv_eval_path = ADV_TEST_SET_PATH if os.path.exists(ADV_TEST_SET_PATH) else None

    baseline_val_acc = None
    baseline_test_acc = None
    baseline_clean_acc = None
    baseline_adv_acc = None
    if os.path.exists(clean_eval_path):
        print("[Setup] Calculating baseline accuracy on Clean/Validation Set...")
        baseline_clean_acc = run_evaluation(memory.current_system_prompt, clean_eval_path, log=False, model_name=target_model_name)
        baseline_val_acc = baseline_clean_acc
        dynamic_threshold = max(0.0, baseline_clean_acc - 0.05)
        print(f"[Setup] Clean baseline: {baseline_clean_acc:.2f}, Dynamic threshold: {dynamic_threshold:.2f}")
    else:
        print("[Setup] Validation set not found. Using a permissive threshold.")
        dynamic_threshold = 0.0

    if adv_eval_path and os.path.exists(adv_eval_path):
        print("[Setup] Calculating baseline accuracy on Adversarial Set...")
        baseline_adv_acc = run_evaluation(memory.current_system_prompt, adv_eval_path, log=False, model_name=target_model_name)
        print(f"[Setup] Adv baseline: {baseline_adv_acc:.2f}")

    if os.path.exists(TEST_SET_PATH):
        print("[Setup] Calculating baseline accuracy on Test Set...")
        baseline_test_acc = run_evaluation(memory.current_system_prompt, TEST_SET_PATH, log=False, model_name=target_model_name)
        print(f"[Setup] Test baseline: {baseline_test_acc:.2f}")
    else:
        print("[Setup] Test set not found. Baseline test accuracy unavailable.")

    # 3. Minimax adversarial loop
    for epoch in range(MAX_EPOCHS):
        print(f"\n--- Epoch {epoch + 1}/{MAX_EPOCHS} ---")
        
        # [Stage A]: Red team selects a seed question and injects distractors
        seed_question, correct_answer = get_random_seed_question()
        red_operator = select_red_operator() if experiment_flags.enable_red_team else None
        if red_operator is not None:
            print(f"[Red Team] Operator: {red_operator.__class__.__name__}")
            adv_question = red_operator.apply_mutation(seed_question)
            print(f"[Red Team] Trap generated. orig_len={len(seed_question)}, adv_len={len(adv_question)}")
        else:
            adv_question = seed_question
            print("[Red Team] Disabled; evaluating the clean seed question directly.")
        
        # [Stage B]: Target model answers with the current best prompt
        current_prompt = memory.current_system_prompt
        prompt_for_target = f"{current_prompt}\n\n[Answer the question]\n{adv_question}"
        
        target_response = target_model.invoke(prompt_for_target)
        
        is_correct = is_correct_response(target_response, correct_answer)
        print(f"  -> (Eval) is_correct={is_correct}")
        
        # [Stage C]: State transition
        if not is_correct and experiment_flags.enable_blue_diagnosis:
            print("[Result] Model failed due to trap. (Red +1, trigger Blue pipeline)")
            if red_operator is not None:
                memory.reward_red_operator(red_operator, score=1)
            blue_trigger_count += 1

            current_rules = [patch.repair_rule for patch in memory.get_active_patches()]
            
            # --- Blue team pipeline ---
            # Step 1: Diagnose
            print("  -> (Blue) Diagnosing failure root cause...")
            try:
                diagnosis_json = blue_committee.diagnose(seed_question, adv_question, target_response, correct_answer)
                failure_node = diagnosis_json.get("failure_node", "Unknown_Vulnerability")
                repair_direction = diagnosis_json.get("repair_direction", "")
            except Exception as e:
                blue_error_count += 1
                print(f"  -> [Blue Error] Diagnose failed: {e}")
                continue

            textual_loss = blue_committee.build_textual_loss(diagnosis_json, is_correct=False) if experiment_flags.enable_textual_loss else ""
            print(f"  -> (Blue) Textual loss encoded: {textual_loss}")
            
            # Step 2: Patch (generate multiple structured candidates)
            print(f"  -> (Blue) Generating candidate patches for: {failure_node}")
            candidate_patch_jsons = []
            try:
                for _ in range(CANDIDATE_PATCHES_PER_ROUND):
                    patch_json = blue_committee.generate_patch(current_rules, failure_node, repair_direction, textual_loss)
                    defense_rule = (patch_json.get("defense_rule") or patch_json.get("proposed_rule", "")).strip()
                    if defense_rule:
                        patch_json["defense_rule"] = defense_rule
                        patch_json["proposed_rule"] = patch_json.get("proposed_rule") or defense_rule
                        patch_json.setdefault("failure_type", failure_node)
                        patch_json.setdefault("attack_type", red_operator.__class__.__name__ if red_operator is not None else "No_Red_Team")
                        patch_json.setdefault("trigger_condition", diagnosis_json.get("vulnerable_segment", "similar adversarial trigger appears"))
                        patch_json.setdefault("scope", "failure_type")
                        patch_json.setdefault("rationale", repair_direction)
                        candidate_patch_jsons.append(patch_json)
            except Exception as e:
                blue_error_count += 1
                print(f"  -> [Blue Error] Patch failed: {e}")
                continue

            if not candidate_patch_jsons:
                blue_error_count += 1
                print("  -> [Blue Error] No candidate patches generated.")
                continue

            # Step 3: Meta-controller orchestration
            print("  -> (Blue) Meta-controller orchestrating update...")
            candidate_patch_summaries = [
                json.dumps(
                    {
                        "failure_type": patch.get("failure_type", failure_node),
                        "trigger_condition": patch.get("trigger_condition", ""),
                        "defense_rule": patch.get("defense_rule", ""),
                        "scope": patch.get("scope", "failure_type"),
                    },
                    ensure_ascii=False,
                )
                for patch in candidate_patch_jsons
            ]
            try:
                if experiment_flags.enable_meta_controller:
                    meta_json = blue_committee.orchestrate_update(
                        current_rules,
                        candidate_patch_summaries,
                        failure_node,
                        textual_loss,
                    )
                    llm_decision = meta_json.get("decision", "reject")
                    selected_patch_text = meta_json.get("selected_patch", "").strip()
                else:
                    llm_decision = "accept"
                    selected_patch_text = candidate_patch_jsons[0].get("defense_rule", "").strip()
            except Exception as e:
                blue_error_count += 1
                print(f"  -> [Blue Error] Meta-controller failed: {e}")
                continue

            selected_patch_json = None
            for patch_json in candidate_patch_jsons:
                defense_rule = patch_json.get("defense_rule", "")
                if selected_patch_text and (selected_patch_text in defense_rule or defense_rule in selected_patch_text):
                    selected_patch_json = patch_json
                    break
            if selected_patch_json is None and llm_decision != "reject":
                selected_patch_json = candidate_patch_jsons[0]
                selected_patch_text = selected_patch_json.get("defense_rule", "").strip()

            print(
                "  -> [Blue Output] "
                f"llm_decision={llm_decision}, selected_len={len(selected_patch_text)}, active_rules={len(current_rules)}"
            )

            if selected_patch_json is not None and llm_decision != "reject" and selected_patch_text:
                patch = memory.build_patch(
                    failure_type=selected_patch_json.get("failure_type", failure_node),
                    attack_type=selected_patch_json.get("attack_type", red_operator.__class__.__name__ if red_operator is not None else "No_Red_Team"),
                    trigger_condition=selected_patch_json.get("trigger_condition", diagnosis_json.get("vulnerable_segment", "")),
                    defense_rule=selected_patch_text,
                    scope=selected_patch_json.get("scope", "failure_type"),
                    source_examples=[adv_question[:800]],
                    rationale=selected_patch_json.get("rationale", repair_direction),
                    created_round=epoch + 1,
                )

                temp_memory = memory.copy()
                temp_memory.add_prompt_patch(patch)
                temp_prompt = temp_memory.get_current_system_prompt()

                print("  -> [Patch Eval] Replaying adversarial sample with candidate patch...")
                replay_response = target_model.invoke(f"{temp_prompt}\n\n[Answer the question]\n{adv_question}")
                replay_correct = is_correct_response(replay_response, correct_answer)
                adv_gain = 1.0 if replay_correct else 0.0

                clean_guard = {
                    "passed": True,
                    "new_clean_acc": last_val_acc if last_val_acc is not None else baseline_clean_acc,
                    "clean_drop": 0.0,
                }
                if experiment_flags.enable_regression_test:
                    clean_reference = last_val_acc if last_val_acc is not None else baseline_clean_acc
                    clean_guard = evaluate_clean_guard(
                        temp_prompt,
                        dynamic_threshold,
                        target_model_name,
                        reference_clean_acc=clean_reference,
                    )

                patch.estimated_adv_gain = adv_gain
                patch.estimated_clean_drop = clean_guard["clean_drop"]
                patch.estimated_clean_risk = clean_guard["clean_drop"]
                if replay_correct:
                    patch.usage_count += 1
                    patch.utility_score += adv_gain
                    patch.last_effective_round = epoch + 1

                eval_result = PatchEvalResult(
                    old_adv_correct=False,
                    new_adv_correct=replay_correct,
                    old_clean_acc=last_val_acc if last_val_acc is not None else baseline_clean_acc,
                    new_clean_acc=clean_guard["new_clean_acc"],
                    adv_gain=adv_gain,
                    clean_drop=clean_guard["clean_drop"],
                )

                if experiment_flags.enable_meta_controller:
                    decision = patch_meta_controller.decide(patch, eval_result)
                    patch_score = patch_meta_controller.score(patch, eval_result)
                else:
                    decision = "accept" if clean_guard["passed"] else "reject"
                    patch_score = adv_gain - clean_guard["clean_drop"]

                print(
                    "  -> [Patch Eval] "
                    f"replay_correct={replay_correct}, adv_gain={adv_gain:.3f}, "
                    f"clean_drop={clean_guard['clean_drop']:.3f}, "
                    f"redundancy={patch.redundancy_score:.3f}, conflict={patch.conflict_score:.3f}, "
                    f"token_cost={patch.token_cost}, score={patch_score:.3f}, controller_decision={decision}"
                )

                if decision in {"accept", "merge"}:
                    if experiment_flags.enable_memory_updates:
                        memory.apply_decision(patch, decision)
                    blue_merge_count += 1
                    print(f"  -> [Memory] Structured patch {decision}ed for node [{failure_node}].")
                    if experiment_flags.enable_memory_updates:
                        episode = memory.record_episode(
                            epoch=epoch + 1,
                            failure_node=failure_node,
                            vulnerable_segment=diagnosis_json.get("vulnerable_segment", ""),
                            repair_direction=repair_direction,
                            textual_loss=textual_loss,
                            decision=decision,
                            is_correct=False,
                            regression_pass=clean_guard["passed"],
                            selected_patch=selected_patch_text,
                            red_operator_name=red_operator.__class__.__name__ if red_operator is not None else "None",
                            patch_id=patch.patch_id,
                            adv_gain=adv_gain,
                            clean_drop=clean_guard["clean_drop"],
                        )
                        policy = memory.update_meta_policy(episode)
                        print(f"  -> [Memory] Meta-policy updated: {policy}")
                else:
                    blue_reject_count += 1
                    print("  -> [Blue Reject] Candidate patch rejected by controller or clean guard.")
                    if experiment_flags.enable_memory_updates:
                        memory.apply_decision(patch, "reject")
                        episode = memory.record_episode(
                            epoch=epoch + 1,
                            failure_node=failure_node,
                            vulnerable_segment=diagnosis_json.get("vulnerable_segment", ""),
                            repair_direction=repair_direction,
                            textual_loss=textual_loss,
                            decision=decision,
                            is_correct=False,
                            regression_pass=clean_guard["passed"],
                            selected_patch=selected_patch_text,
                            red_operator_name=red_operator.__class__.__name__ if red_operator is not None else "None",
                            patch_id=patch.patch_id,
                            adv_gain=adv_gain,
                            clean_drop=clean_guard["clean_drop"],
                        )
                        policy = memory.update_meta_policy(episode)
                        print(f"  -> [Memory] Meta-policy updated: {policy}")
            else:
                decision = "reject"
                blue_reject_count += 1
                print("  -> [Blue Reject] Meta-controller rejected the patch.")
                if experiment_flags.enable_memory_updates:
                    episode = memory.record_episode(
                        epoch=epoch + 1,
                        failure_node=failure_node,
                        vulnerable_segment=diagnosis_json.get("vulnerable_segment", ""),
                        repair_direction=repair_direction,
                        textual_loss=textual_loss,
                        decision=decision,
                        is_correct=False,
                        regression_pass=None,
                        selected_patch=selected_patch_text,
                        red_operator_name=red_operator.__class__.__name__ if red_operator is not None else "None",
                    )
                    policy = memory.update_meta_policy(episode)
                    print(f"  -> [Memory] Meta-policy updated: {policy}")
                
        else:
            print("[Result] Model defended successfully. (Red -1)")
            if red_operator is not None:
                memory.reward_red_operator(red_operator, score=-1)
            if experiment_flags.enable_memory_updates:
                print("  -> (Blue) Attributing credit to active patches...")
                for patch in memory.get_active_patches():
                    patch.utility_score += 1.0
                    patch.usage_count += 1
                    patch.last_effective_round = epoch + 1
                success_episode = memory.record_episode(
                    epoch=epoch + 1,
                    failure_node="No_Failure",
                    vulnerable_segment="",
                    repair_direction="",
                    textual_loss=blue_committee.build_textual_loss({}, is_correct=True) if experiment_flags.enable_textual_loss else "",
                    decision="accept",
                    is_correct=True,
                    regression_pass=True,
                    selected_patch="",
                    red_operator_name=red_operator.__class__.__name__ if red_operator is not None else "None",
                )
                policy = memory.update_meta_policy(success_episode)
                print(f"  -> [Memory] Meta-policy updated: {policy}")
            
        # --- Evaluate current prompt after each epoch ---
        print(f"--- Evaluating prompt for epoch {epoch+1} ---")
        current_prompt = memory.current_system_prompt
        clean_acc = None
        adv_acc = None
        
        if os.path.exists(clean_eval_path) and os.path.exists(TRAIN_SET_PATH):
            print(
                "  -> [Prompt Eval] "
                f"prompt_len={len(current_prompt)}, "
                f"max_samples={EVAL_MAX_SAMPLES}, "
                f"seed={EVAL_RANDOM_SEED}"
            )
            val_acc = run_evaluation(current_prompt, clean_eval_path, log=True, model_name=target_model_name)
            train_acc = run_evaluation(current_prompt, TRAIN_SET_PATH, log=True, model_name=target_model_name)
            clean_acc = val_acc
            if adv_eval_path and experiment_flags.evaluate_adv_set:
                adv_acc = run_evaluation(current_prompt, adv_eval_path, log=True, model_name=target_model_name)
            memory.log_epoch(
                epoch + 1,
                val_acc,
                train_acc,
                clean_acc=clean_acc,
                adv_acc=adv_acc,
                blue_trigger_count=blue_trigger_count,
                blue_merge_count=blue_merge_count,
                blue_reject_count=blue_reject_count,
                blue_error_count=blue_error_count,
            )
            print(f"  -> Current scores: val {val_acc*100:.1f}%, train {train_acc*100:.1f}%")
            last_val_acc = val_acc
            last_train_acc = train_acc
        else:
            print("  -> No split sets found. Run scripts/generate_benchmark.py first.")

        if experiment_flags.enable_pruning:
            pruned_count = memory.prune_patches()
            if pruned_count > 0:
                print(f"  -> [Pruner] Deactivated {pruned_count} low-utility or conflicting patch(es).")

        if experiment_flags.enable_abstraction:
            active_patches = memory.get_active_patches()
            patches_by_node = {}
            for patch in active_patches:
                patches_by_node.setdefault(patch.failure_node, []).append(patch)

            for failure_node, node_patches in patches_by_node.items():
                if len(node_patches) < 3:
                    continue

                current_rules = [patch.repair_rule for patch in active_patches]
                candidate_rules = [patch.repair_rule for patch in node_patches]
                print(f"  -> [Pruner] Abstracting {len(node_patches)} patches for node [{failure_node}]...")
                try:
                    prune_json = blue_committee.prune(current_rules, failure_node, candidate_rules)
                    generalized_rule = prune_json.get("compressed_prompt", "").strip()
                except Exception as e:
                    blue_error_count += 1
                    print(f"  -> [Blue Error] Pruner failed: {e}")
                    continue

                if not generalized_rule or generalized_rule in candidate_rules:
                    print("  -> [Pruner] No generalized rule produced.")
                    continue

                if experiment_flags.enable_memory_updates:
                    for patch in node_patches:
                        patch.is_active = False
                    memory.add_patch(failure_node, generalized_rule)
                    print(f"  -> [Pruner] Generalized patch deployed for node [{failure_node}].")
            
    # End of loop, print results
    print("\n========== S-MAPE adversarial evolution finished ==========")
    print(f"-> Final system prompt:\n{memory.current_system_prompt}\n")
    print(f"-> Final active patches:\n{[patch.__dict__ for patch in memory.get_active_patches()]}")
    print(f"-> Red team operator scores:\n{memory.red_team_scores}")
    print(
        "-> Blue team stats: "
        f"triggered={blue_trigger_count}, merged={blue_merge_count}, "
        f"rejected={blue_reject_count}, errors={blue_error_count}"
    )

    if last_val_acc is not None and last_train_acc is not None:
        out_dir = str(output_dir)
        
        # Save final metrics and config
        out_path = os.path.join(out_dir, "final_metrics.json")
        final_metrics = {
            "experiment_preset": EXPERIMENT_PRESET,
            "experiment_flags": experiment_flags_to_dict(experiment_flags),
            "output_dir": out_dir,
            "seed": EVAL_RANDOM_SEED,
            "val_acc": last_val_acc,
            "train_acc": last_train_acc,
            "clean_acc": last_val_acc,
            "adv_acc": adv_acc,
            "eval_max_samples": EVAL_MAX_SAMPLES,
            "eval_random_seed": EVAL_RANDOM_SEED,
            "final_system_prompt": memory.current_system_prompt,
            "active_patches": [patch.__dict__ for patch in memory.get_active_patches()],
            "baseline_val_acc": baseline_val_acc,
            "baseline_clean_acc": baseline_clean_acc,
            "baseline_adv_acc": baseline_adv_acc,
            "baseline_test_acc": baseline_test_acc
            ,"blue_trigger_count": blue_trigger_count,
            "blue_merge_count": blue_merge_count,
            "blue_reject_count": blue_reject_count,
            "blue_error_count": blue_error_count,
        }
        with open(out_path, "w", encoding="utf-8") as f:
            json.dump(final_metrics, f, ensure_ascii=False, indent=2)
            
        # Save the final prompt to a text file for easy reuse
        prompt_out_path = os.path.join(out_dir, "final_prompt.txt")
        with open(prompt_out_path, "w", encoding="utf-8") as f:
            f.write(memory.current_system_prompt)
            
        print(f"-> Final metrics written: {out_path}")
        print(f"-> Final prompt written: {prompt_out_path}")
        
        print("\n========== Starting final evaluation on full dataset ==========")
        full_dataset_path = TEST_SET_PATH
        if os.path.exists(full_dataset_path):
            print(f"-> Full evaluation file: {full_dataset_path}")
            # Use max_samples=0 to disable sampling and evaluate the full dataset
            final_full_acc = run_evaluation(
                memory.current_system_prompt,
                full_dataset_path,
                log=True,
                max_samples=0,
                model_name=target_model_name
            )
            print(f"-> Final full-dataset accuracy: {final_full_acc * 100:.1f}%")

            # Append full-dataset accuracy to metrics
            final_metrics["final_full_dataset_acc"] = final_full_acc
            with open(out_path, "w", encoding="utf-8") as f:
                json.dump(final_metrics, f, ensure_ascii=False, indent=2)
        else:
            print("-> Full evaluation skipped: test set not found.")


if __name__ == '__main__':
    main()
